# Generated by Django 2.2.5 on 2020-04-25 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefactoryUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_Contact', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_Contact', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Sir', 'Sir'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=6)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('id', models.CharField(default='u-200425s6e132320-r485317 ', max_length=254, primary_key=True, serialize=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('id', models.IntegerField(default=1)),
                ('accessibility_id', models.CharField(default='ACC/XXX', max_length=10, primary_key=True, serialize=False)),
                ('accessibility_name', models.CharField(max_length=20)),
                ('accessibility_description', models.TextField(max_length=255)),
                ('accessibility_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Accessibility',
                'ordering': ['accessibility_id'],
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('administrator_id', models.CharField(default='REF/SOAP/ADM/XX', max_length=17, primary_key=True, serialize=False)),
                ('id', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['administrator_id'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementChannelSet',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=20)),
                ('description', models.TextField(default='Channel set', max_length=255)),
            ],
            options={
                'ordering': ['channel_id'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementSubChannelSet',
            fields=[
                ('sub_channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_channel_name', models.CharField(max_length=20)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.AdvertisementChannelSet')),
            ],
            options={
                'ordering': ['sub_channel_name'],
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant_id', models.CharField(default='REF/SOAP/APT/20/04/25132320 ', max_length=254, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('applicant_Photo', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('dateofBirth', models.DateField(blank=True, null=True)),
                ('town_Residential', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['applicant_id'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.CharField(default='RFCT/SOAP/APP/20/04/625132320522298 ', max_length=254, primary_key=True, serialize=False)),
                ('application_status', models.CharField(choices=[('incomplete', 'Incomplete Application'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='incomplete', max_length=10)),
                ('recruitment_state', models.CharField(choices=[('incomplete', 'Incomplete Application'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='pending', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
            ],
            options={
                'ordering': ['application_id'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.CharField(default='BCH-530278 ', max_length=254, primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('date_of_last_update', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['batch_id'],
            },
        ),
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('bootcamp_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bootcamp_name', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bootcamp_number', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('running', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['bootcamp_id'],
            },
        ),
        migrations.CreateModel(
            name='Catalyst',
            fields=[
                ('catalyst_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('catalyst_name', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('catalyst_number', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('running', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['catalyst_id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryStructure',
            fields=[
                ('interview_category', models.CharField(choices=[('catalyst', 'Catalyst Interviews'), ('bootcamp', 'Bootcamp Interviews')], default='Catalyst', max_length=20)),
                ('structure_id', models.AutoField(primary_key=True, serialize=False)),
                ('structure_name', models.CharField(max_length=254)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('cohort_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cohort_name', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cohort_number', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('running', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['cohort_id'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interview_id', models.CharField(default='INTV-200425-6-132320-539270 ', max_length=254, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSet',
            fields=[
                ('set_id', models.CharField(default='INTV-SET-200425-6-132320-532277 ', max_length=254, primary_key=True, serialize=False)),
                ('set_name', models.CharField(max_length=254)),
                ('interview_category', models.CharField(choices=[('Catalyst', 'Catalyst Interviews'), ('Bootcamp', 'Bootcamp Interviews')], default='Catalyst', max_length=20)),
                ('Field_of_study', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('running', models.BooleanField()),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.CharField(default='REF/SOAP/PTN/XXX', max_length=17, primary_key=True, serialize=False)),
                ('id', models.IntegerField(default=1)),
                ('partner_name', models.CharField(max_length=30)),
                ('partner_logo', models.ImageField(upload_to='')),
                ('partner_cover_photo', models.ImageField(upload_to='')),
                ('partner_description', models.TextField(max_length=500)),
                ('partnership_type', models.CharField(choices=[('Industrial', 'Industrial'), ('Project', 'Project')], max_length=15)),
                ('administrator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Administrator')),
            ],
            options={
                'ordering': ['partner_id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(default=1)),
                ('role_id', models.CharField(default='RL-XXX', max_length=10, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=254)),
                ('role_description', models.TextField(max_length=100)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['role_id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(default=1)),
                ('room_id', models.CharField(default='RM-XXX', max_length=10, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=254)),
                ('block_level', models.CharField(max_length=254)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'ordering': ['room_id'],
            },
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'ordering': ['skill_id'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(default='REF/SOAP/STF/XXX', max_length=20, primary_key=True, serialize=False)),
                ('id', models.IntegerField(default=1)),
                ('staff_Photo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Partner')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['staff_id'],
            },
        ),
        migrations.CreateModel(
            name='StructureIndicator',
            fields=[
                ('indicator_id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator_name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('structure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.CategoryStructure')),
            ],
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Role')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Staff')),
            ],
            options={
                'ordering': ['staff_id'],
            },
        ),
        migrations.CreateModel(
            name='StaffAccessibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Accessibility')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Staff')),
            ],
            options={
                'verbose_name_plural': 'Staff Accessibility',
                'ordering': ['staff_id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.SkillSet')),
            ],
            options={
                'ordering': ['applicant_id'],
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=255)),
                ('organisation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('telephone', models.CharField(max_length=40)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
            ],
            options={
                'ordering': ['applicant_id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('association', models.CharField(max_length=255)),
                ('project_url', models.URLField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=255)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
            ],
            options={
                'ordering': ['applicant_id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Partner')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Role')),
            ],
            options={
                'ordering': ['partner_id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerAccessibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Accessibility')),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Partner')),
            ],
            options={
                'verbose_name_plural': 'Partner Accessibility',
                'ordering': ['partner_id'],
            },
        ),
        migrations.CreateModel(
            name='Panelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Batch')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Staff')),
            ],
            options={
                'ordering': ['batch_id'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSelection',
            fields=[
                ('selection_id', models.CharField(default='INTV-SLCT-200425-6-132320-533276 ', max_length=254, primary_key=True, serialize=False)),
                ('selection_date', models.DateTimeField()),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Application')),
                ('set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.InterviewSet')),
            ],
            options={
                'ordering': ['-selection_date'],
            },
        ),
        migrations.CreateModel(
            name='InterviewScore',
            fields=[
                ('score_id', models.CharField(default='5402690413256202320 ', max_length=254, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('comment', models.TextField(max_length=255)),
                ('indicator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.StructureIndicator')),
                ('interview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Interview')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('schedule_id', models.CharField(default='INTV-SCHDL-200425-6-132320-534276 ', max_length=254, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Batch')),
                ('selection_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='refactory.InterviewSelection')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='schedule_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='refactory.InterviewSchedule'),
        ),
        migrations.CreateModel(
            name='EducationBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('BSCS', 'Computer Science'), ('LLB', 'Lawyer'), ('BSIT', 'Information Technology')], default='BSCS', max_length=4)),
                ('Field_of_study', models.CharField(max_length=255)),
                ('grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=255)),
                ('From', models.DateTimeField(default=django.utils.timezone.now)),
                ('to', models.DateTimeField(default=django.utils.timezone.now)),
                ('Extra_activity', models.TextField(max_length=255)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
            ],
            options={
                'ordering': ['to'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_link', models.URLField(max_length=255)),
                ('twitter_link', models.URLField(max_length=255)),
                ('facebook_link', models.URLField(max_length=255)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Application')),
            ],
            options={
                'ordering': ['application_id'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_title', models.CharField(max_length=20)),
                ('License', models.CharField(max_length=255)),
                ('certificate_url', models.URLField()),
                ('certificate_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=255)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
            ],
            options={
                'ordering': ['applicant_id'],
            },
        ),
        migrations.CreateModel(
            name='CatalystApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='refactory.Application')),
                ('catalyst_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Catalyst')),
            ],
            options={
                'ordering': ['catalyst_id'],
            },
        ),
        migrations.CreateModel(
            name='BootcampApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='refactory.Application')),
                ('bootcamp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Bootcamp')),
            ],
            options={
                'ordering': ['bootcamp_id'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Room'),
        ),
        migrations.CreateModel(
            name='ApplicationVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videolink', models.URLField(max_length=255)),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Application')),
            ],
            options={
                'ordering': ['application_id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantChannelSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
                ('sub_channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.AdvertisementSubChannelSet')),
            ],
            options={
                'ordering': ['applicant_id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantAccessibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Accessibility')),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
            ],
            options={
                'verbose_name_plural': 'Applicant Accessibility',
                'ordering': ['applicant_id'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('admission_id', models.CharField(default='ADMSN-200425-6-132320-542269 ', max_length=254, primary_key=True, serialize=False)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('application_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='refactory.Application')),
            ],
            options={
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='AdministratorRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Administrator')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Role')),
            ],
            options={
                'ordering': ['administrator_id'],
            },
        ),
        migrations.CreateModel(
            name='AdministratorAccessibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Accessibility')),
                ('administrator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Administrator')),
            ],
            options={
                'verbose_name_plural': 'Administrator Accessibility',
                'ordering': ['administrator_id'],
            },
        ),
    ]
