# Generated by Django 2.2.5 on 2019-10-29 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefactoryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('sur_name', models.CharField(blank=True, max_length=255, null=True)),
                ('given_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_Contact', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_Contact', models.CharField(blank=True, max_length=255, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('accessibility_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('accessibility_name', models.CharField(max_length=20)),
                ('accessibility_description', models.TextField(max_length=255)),
                ('accessibility_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_Photo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('admission_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementChannelSet',
            fields=[
                ('channel_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('applicant_Photo', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('dateofBirth', models.DateField(blank=True, null=True)),
                ('town_Residential', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videolink', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('bootcamp_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bootcamp_name', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bootcamp_number', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('running', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalyst',
            fields=[
                ('catalyst_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('catalyst_name', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('catalyst_number', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('running', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('cohort_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cohort_name', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cohort_number', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('running', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interview_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('schedule_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20)),
                ('role_description', models.TextField(max_length=20)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('skill_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_Photo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='refactory.Administrator')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Role')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffAccessibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Administrator')),
                ('accessibility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Accessibility')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.SkillSet')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=255)),
                ('organisation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('telephone', models.CharField(max_length=40)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_title', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=255)),
                ('publication_url', models.URLField()),
                ('publication_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=255)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('association', models.CharField(max_length=255)),
                ('project_url', models.URLField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=255)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Role')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerAccessibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Accessibility')),
            ],
        ),
        migrations.CreateModel(
            name='Panelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewScore',
            fields=[
                ('indicator_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('comment', models.TextField(max_length=255)),
                ('interview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Interview')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honor_title', models.CharField(max_length=255)),
                ('association', models.CharField(max_length=255)),
                ('Issuer', models.CharField(max_length=255)),
                ('date_of_honor', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=255)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='EducationBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('BSCS', 'Computer Science'), ('LLB', 'Lawyer'), ('BSIT', 'Information Technology')], default='BSCS', max_length=4)),
                ('Field_of_study', models.CharField(max_length=255)),
                ('grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=255)),
                ('From', models.DateTimeField(default=django.utils.timezone.now)),
                ('to', models.DateTimeField(default=django.utils.timezone.now)),
                ('Extra_activity', models.TextField(max_length=255)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_id', models.CharField(max_length=255)),
                ('association', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_link', models.URLField(max_length=255)),
                ('twitter_link', models.URLField(max_length=255)),
                ('facebook_link', models.URLField(max_length=255)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_title', models.CharField(max_length=20)),
                ('License', models.CharField(max_length=255)),
                ('certificate_url', models.URLField()),
                ('certificate_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=255)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantAccessibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Accessibility')),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Applicant')),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.AdvertisementChannelSet')),
            ],
        ),
        migrations.CreateModel(
            name='AdministratorRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Administrator')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Role')),
            ],
        ),
        migrations.CreateModel(
            name='AdministratorAccessibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Accessibility')),
                ('administrator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refactory.Administrator')),
            ],
        ),
    ]
