# Generated by Django 2.2.4 on 2019-09-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refactory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refactoryuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refactoryuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
