# Generated by Django 2.2.4 on 2019-09-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refactory', '0002_auto_20190925_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='Admin_Photo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='DateofBirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Nationality',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Town_Residential',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='applicant_Photo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='refactoryuser',
            name='Primary_Contact',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='refactoryuser',
            name='Secondary_Contact',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Staff_Photo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
