# Generated by Django 2.2.5 on 2019-10-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refactory', '0004_auto_20190927_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupildetails',
            name='pd_id',
        ),
        migrations.AlterField(
            model_name='refactoryuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='pupil',
        ),
        migrations.DeleteModel(
            name='pupildetails',
        ),
    ]
